{
  "swagger" : "2.0",
  "info" : {
    "description" : "Card token web api.",
    "version" : "1.0.0",
    "title" : "Cardtoken.io"
  },
  "host" : "virtserver.swaggerhub.com",
  "basePath" : "/cloudfy/cardtoken/1.0.0",
  "tags" : [ {
    "name" : "card"
  }, {
    "name" : "gateway"
  }, {
    "name" : "merchant"
  }, {
    "name" : "tenant"
  }, {
    "name" : "token"
  } ],
  "schemes" : [ "https" ],
  "consumes" : [ "application/json" ],
  "produces" : [ "application/json" ],
  "security" : [ {
    "basicAuth" : [ ]
  } ],
  "paths" : {
    "/tenant/" : {
      "post" : {
        "tags" : [ "tenant" ],
        "summary" : "Create a tenant",
        "description" : "Create a new tenant.",
        "parameters" : [ {
          "in" : "body",
          "name" : "tenant",
          "description" : "XX",
          "required" : true,
          "schema" : {
            "$ref" : "#/definitions/createTenantRequest"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "OK",
            "schema" : {
              "$ref" : "#/definitions/tenant"
            }
          },
          "400" : {
            "description" : "A parameter of required query is not provided or validation failed."
          },
          "500" : {
            "description" : "An error was unhandled on the server.",
            "examples" : {
              "application/json" : {
                "message" : "string"
              }
            }
          }
        }
      }
    },
    "/token/" : {
      "get" : {
        "tags" : [ "token" ],
        "summary" : "/token/",
        "description" : "Returns a list of tokens.",
        "parameters" : [ ],
        "responses" : {
          "200" : {
            "description" : "OK",
            "schema" : {
              "$ref" : "#/definitions/tokenCollection"
            }
          },
          "401" : {
            "description" : "Unauthorized access. Please verify the API key and permission scope.",
            "headers" : {
              "authorization" : {
                "type" : "string",
                "description" : "Basic."
              }
            }
          },
          "500" : {
            "description" : "An error was unhandled on the server.",
            "examples" : {
              "application/json" : {
                "message" : "string"
              }
            }
          }
        }
      }
    },
    "/token/{token}/" : {
      "get" : {
        "tags" : [ "token" ],
        "summary" : "/token/{token}",
        "description" : "Returns a token by handle.",
        "parameters" : [ {
          "name" : "token",
          "in" : "path",
          "description" : "Token of card.",
          "required" : true,
          "type" : "string"
        } ],
        "responses" : {
          "200" : {
            "description" : "OK",
            "schema" : {
              "$ref" : "#/definitions/token"
            }
          },
          "401" : {
            "description" : "Unauthorized access. Please verify the API key and permission scope.",
            "headers" : {
              "authorization" : {
                "type" : "string",
                "description" : "Basic."
              }
            }
          },
          "500" : {
            "description" : "An error was unhandled on the server.",
            "examples" : {
              "application/json" : {
                "message" : "string"
              }
            }
          }
        }
      }
    },
    "/card/" : {
      "get" : {
        "tags" : [ "card" ],
        "summary" : "/card/",
        "description" : "Returns a list of cards.",
        "parameters" : [ ],
        "responses" : {
          "200" : {
            "description" : "OK"
          },
          "401" : {
            "description" : "Unauthorized access. Please verify the API key and permission scope.",
            "headers" : {
              "authorization" : {
                "type" : "string",
                "description" : "Basic."
              }
            }
          },
          "500" : {
            "description" : "An error was unhandled on the server.",
            "examples" : {
              "application/json" : {
                "message" : "string"
              }
            }
          }
        }
      },
      "post" : {
        "tags" : [ "card" ],
        "summary" : "/card/",
        "description" : "Post a card or token.",
        "parameters" : [ {
          "in" : "body",
          "name" : "card",
          "description" : "xx",
          "required" : true,
          "schema" : {
            "$ref" : "#/definitions/card"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "OK",
            "schema" : {
              "$ref" : "#/definitions/token"
            }
          },
          "401" : {
            "description" : "Unauthorized access. Please verify the API key and permission scope.",
            "headers" : {
              "authorization" : {
                "type" : "string",
                "description" : "Basic."
              }
            }
          },
          "500" : {
            "description" : "An error was unhandled on the server.",
            "examples" : {
              "application/json" : {
                "message" : "string"
              }
            }
          }
        },
        "security" : [ {
          "basicAuth" : [ ]
        } ]
      }
    },
    "/merchant/" : {
      "get" : {
        "tags" : [ "merchant" ],
        "summary" : "/merchant/",
        "description" : "Returns a list of merchants.",
        "parameters" : [ ],
        "responses" : {
          "200" : {
            "description" : "OK",
            "schema" : {
              "$ref" : "#/definitions/merchantCollection"
            }
          },
          "401" : {
            "description" : "Unauthorized access. Please verify the API key and permission scope.",
            "headers" : {
              "authorization" : {
                "type" : "string",
                "description" : "Basic."
              }
            }
          },
          "500" : {
            "description" : "An error was unhandled on the server.",
            "examples" : {
              "application/json" : {
                "message" : "string"
              }
            }
          }
        }
      },
      "post" : {
        "tags" : [ "merchant" ],
        "summary" : "/merchant/",
        "description" : "Creates a new merchant",
        "parameters" : [ {
          "in" : "body",
          "name" : "merchant",
          "description" : "xx",
          "required" : true,
          "schema" : {
            "$ref" : "#/definitions/merchant"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "OK"
          },
          "401" : {
            "description" : "Unauthorized access. Please verify the API key and permission scope.",
            "headers" : {
              "authorization" : {
                "type" : "string",
                "description" : "Basic."
              }
            }
          },
          "500" : {
            "description" : "An error was unhandled on the server.",
            "examples" : {
              "application/json" : {
                "message" : "string"
              }
            }
          }
        }
      }
    },
    "/gateway/" : {
      "post" : {
        "tags" : [ "gateway" ],
        "summary" : "/gateway/",
        "description" : "Creates a new gateway",
        "parameters" : [ {
          "in" : "body",
          "name" : "gateway",
          "description" : "xx",
          "required" : true,
          "schema" : {
            "$ref" : "#/definitions/gateway"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "OK",
            "schema" : {
              "$ref" : "#/definitions/gateway"
            }
          },
          "401" : {
            "description" : "Unauthorized access. Please verify the API key and permission scope.",
            "headers" : {
              "authorization" : {
                "type" : "string",
                "description" : "Basic."
              }
            }
          },
          "500" : {
            "description" : "An error was unhandled on the server.",
            "examples" : {
              "application/json" : {
                "message" : "string"
              }
            }
          }
        }
      }
    }
  },
  "securityDefinitions" : {
    "basicAuth" : {
      "description" : "xx",
      "type" : "basic"
    }
  },
  "definitions" : {
    "tokenCollection" : {
      "type" : "object",
      "properties" : {
        "collection" : {
          "type" : "array",
          "description" : "Array of token.",
          "items" : {
            "$ref" : "#/definitions/token"
          }
        }
      },
      "example" : {
        "collection" : [ {
          "metadata" : [ {
            "value" : "value",
            "key" : "key"
          }, {
            "value" : "value",
            "key" : "key"
          } ],
          "maskedcard" : "maskedcard",
          "createddate" : "today",
          "fingerprint" : "fingerprint",
          "exp_month" : 0,
          "id" : "id",
          "exp_year" : 6,
          "cardholder" : "cardholder",
          "brand" : "brand",
          "token" : "token"
        }, {
          "metadata" : [ {
            "value" : "value",
            "key" : "key"
          }, {
            "value" : "value",
            "key" : "key"
          } ],
          "maskedcard" : "maskedcard",
          "createddate" : "today",
          "fingerprint" : "fingerprint",
          "exp_month" : 0,
          "id" : "id",
          "exp_year" : 6,
          "cardholder" : "cardholder",
          "brand" : "brand",
          "token" : "token"
        } ]
      }
    },
    "token" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "type" : "string",
          "description" : "Guid."
        },
        "cardholder" : {
          "type" : "string",
          "description" : "Cardholder name"
        },
        "token" : {
          "type" : "string",
          "description" : "token of the card"
        },
        "exp_month" : {
          "type" : "integer"
        },
        "exp_year" : {
          "type" : "integer"
        },
        "maskedcard" : {
          "type" : "string",
          "description" : "Masked card 4134xxxxxxxx1234"
        },
        "brand" : {
          "type" : "string",
          "description" : "Brand of card, example VISA."
        },
        "fingerprint" : {
          "type" : "string"
        },
        "metadata" : {
          "type" : "array",
          "items" : {
            "$ref" : "#/definitions/metadata"
          }
        },
        "createddate" : {
          "type" : "string",
          "description" : "Date in UTC format. yyyy-mm-dd",
          "title" : "created date",
          "pattern" : "yyyy-mm-dd",
          "default" : "today"
        }
      },
      "example" : {
        "metadata" : [ {
          "value" : "value",
          "key" : "key"
        }, {
          "value" : "value",
          "key" : "key"
        } ],
        "maskedcard" : "maskedcard",
        "createddate" : "today",
        "fingerprint" : "fingerprint",
        "exp_month" : 0,
        "id" : "id",
        "exp_year" : 6,
        "cardholder" : "cardholder",
        "brand" : "brand",
        "token" : "token"
      }
    },
    "metadata" : {
      "type" : "object",
      "properties" : {
        "key" : {
          "type" : "string"
        },
        "value" : {
          "type" : "string"
        }
      },
      "example" : {
        "value" : "value",
        "key" : "key"
      }
    },
    "tenant" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "type" : "string",
          "description" : "Guid"
        },
        "name" : {
          "type" : "string"
        },
        "email" : {
          "type" : "string"
        },
        "apiKey" : {
          "type" : "string"
        }
      },
      "example" : {
        "apiKey" : "apiKey",
        "name" : "name",
        "id" : "id",
        "email" : "email"
      }
    },
    "card" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "type" : "string",
          "description" : "Guid"
        },
        "token" : {
          "type" : "string",
          "description" : "X",
          "pattern" : "XXXXXXXXXXX"
        },
        "tokengateway" : {
          "type" : "string",
          "description" : "X"
        },
        "cardholder" : {
          "type" : "string",
          "description" : "Cardholder name"
        },
        "number" : {
          "type" : "string"
        },
        "exp_month" : {
          "type" : "integer"
        },
        "exp_year" : {
          "type" : "integer"
        },
        "cvc" : {
          "type" : "string",
          "description" : "security number.",
          "minLength" : 3,
          "maxLength" : 4
        },
        "metadata" : {
          "type" : "array",
          "items" : {
            "$ref" : "#/definitions/metadata"
          }
        },
        "createddate" : {
          "type" : "string",
          "description" : "Date in UTC format. yyyy-mm-dd",
          "title" : "created date",
          "pattern" : "yyyy-mm-dd",
          "default" : "today"
        }
      }
    },
    "merchantCollection" : {
      "type" : "object",
      "properties" : {
        "collection" : {
          "type" : "array",
          "description" : "Array of merchant.",
          "items" : {
            "$ref" : "#/definitions/merchant"
          }
        }
      },
      "example" : {
        "collection" : [ {
          "privatekey" : "privatekey",
          "createddate" : "today",
          "name" : "name",
          "publickey" : "publickey",
          "id" : "id"
        }, {
          "privatekey" : "privatekey",
          "createddate" : "today",
          "name" : "name",
          "publickey" : "publickey",
          "id" : "id"
        } ]
      }
    },
    "merchant" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "type" : "string",
          "description" : "Guid"
        },
        "name" : {
          "type" : "string"
        },
        "publickey" : {
          "type" : "string",
          "description" : "Key used for handling cards online using cardtoken.js."
        },
        "privatekey" : {
          "type" : "string",
          "description" : "API key. Not shareable."
        },
        "createddate" : {
          "type" : "string",
          "description" : "Date in UTC format. yyyy-mm-dd",
          "title" : "created date",
          "pattern" : "yyyy-mm-dd",
          "default" : "today"
        }
      },
      "example" : {
        "privatekey" : "privatekey",
        "createddate" : "today",
        "name" : "name",
        "publickey" : "publickey",
        "id" : "id"
      }
    },
    "createTenantRequest" : {
      "type" : "object",
      "properties" : {
        "name" : {
          "type" : "string"
        },
        "email" : {
          "type" : "string"
        }
      }
    },
    "gateway" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "type" : "string",
          "description" : "Guid"
        },
        "name" : {
          "type" : "string"
        },
        "gatewaytype" : {
          "type" : "string"
        },
        "createddate" : {
          "type" : "string",
          "description" : "Date in UTC format. yyyy-mm-dd",
          "title" : "created date",
          "pattern" : "yyyy-mm-dd",
          "default" : "today"
        }
      },
      "example" : {
        "name" : "test",
        "gatewaytype" : "test"
      }
    }
  },
  "responses" : {
    "BadRequest" : {
      "description" : "A parameter of required query is not provided or validation failed."
    },
    "InternalServerError" : {
      "description" : "An error was unhandled on the server.",
      "examples" : {
        "application/json" : {
          "message" : "string"
        }
      }
    },
    "NoContent" : {
      "description" : "Resource updated/deleted successfully."
    },
    "NotFound" : {
      "description" : "The specified resource was not found."
    },
    "Unauthorized" : {
      "description" : "Unauthorized access. Please verify the API key and permission scope.",
      "headers" : {
        "authorization" : {
          "type" : "string",
          "description" : "Basic."
        }
      }
    }
  }
}
